project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
      - text: Hands-on Exercises
        menu:
          - text: "1: A Layered Grammar of Graphics: ggplot2 methods"
            href: Hands-on_Exs/Ex1/Hands-on_Ex1.qmd
      - text: In-class Exercises
        menu:
          - text: "1: Introduction to Visual Analytics"
            href: In-class_Exs/Ex1/In-class_Ex1.qmd
      - text: Take-home Exercises
        menu:
          - text: "To be filled"
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual