project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
      - text: Hands-on Exercises
        menu:
          - text: "1: A Layered Grammar of Graphics: ggplot2 methods"
            href: Hands-on_Exs/Ex1/Hands-on_Ex1.qmd
          - text: "2: Beyond ggplot Fundamentals"
            href: Hands-on_Exs/Ex2/Hands-on_Ex2.qmd
          - text: "3A: Programming Interactive Data Visualisation with R"
            href: Hands-on_Exs/Ex3A/Hands-on_Ex3A.qmd
          - text: "3B: Programming Animated Statistical Graphics with R"
            href: Hands-on_Exs/Ex3B/Hands-on_Ex3B.qmd
          - text: "4A: Visualizing Statistical Analysis"
            href: Hands-on_Exs/Ex4A/Hands-on_Ex4A.qmd
          - text: "4B: Visualizing Uncertainty"
            href: Hands-on_Exs/Ex4B/Hands-on_Ex4B.qmd
          - text: "4C: Building Funnel Plot with R"
            href: Hands-on_Exs/Ex4C/Hands-on_Ex4C.qmd
          - text: "5: Visualising and Analysing Text Data"
            href: Hands-on_Exs/Ex5/Hands-on_Ex5.qmd
          - text: "6: Visualising and Analysing Network Data"
            href: Hands-on_Exs/Ex6/Hands-on_Ex6.qmd
      - text: In-class Exercises
        menu:
          - text: "1: Introduction to Visual Analytics"
            href: In-class_Exs/Ex1/In-class_Ex1.qmd
          - text: "2: Visualizing Distribution"
            href: In-class_Exs/Ex2/In-class_Ex2.qmd
          - text: "4: Visualizing Uncertainty"
            href: In-class_Exs/Ex4/In-class_Ex4.qmd
          - text: "5: Visualising and Analysing Text Data"
            href: In-class_Exs/Ex5/In-class_Ex5.qmd
          - text: "6A: Visualising and Analysing Text Data (Part 2)"
            href: In-class_Exs/Ex6A/In-class_Ex6A.qmd
          - text: "6B: Visualising and Analysing Network Data"
            href: In-class_Exs/Ex6B/In-class_Ex6B.qmd
      - text: Take-home Exercises
        menu:
          - text: "1: Singapore Private Residential Property Market for 2024 Q1"
            href: Take-home_Exs/Ex1/Take-home_Ex1.qmd
          - text: "2: DataVis Makeover"
            href: Take-home_Exs/Ex2/Take-home_Ex2.qmd
          - text: "3: VAST Challenge 2024 Mini-Challenge 3"
            href: Take-home_Exs/Ex3/Take-home_Ex3.qmd
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual